theme = "icy"

[editor]
gutters = ["diff", "line-numbers", "spacer", "diagnostics", "spacer"]
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true
auto-save = true
true-color = true
scrolloff = 999
idle-timeout = 0
completion-trigger-len = 1

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spacer", "spinner", "diagnostics"]
right = [
  "diagnostics",
  "selections",
  "position",
  "position-percentage",
  "file-encoding",
]

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[keys.normal]
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.normal.g]
j = "jump_forward"
k = "jump_backward"
q = ":reflow"

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"

[keys.normal.space.w]
V = ["vsplit_new", "file_picker"]
S = ["hsplit_new", "file_picker"]
