[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }
deno = { command = "deno", args = ["lsp"] }
emmet-ls = { command = "emmet-ls", args = ["--stdio"] }

[[language]]
name = "c"
indent = { tab-width = 8, unit = " " }
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "python"
indent = { tab-width = 4, unit = "  " }
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "swift"
language-servers = ["sourcekit-lsp"]
formatter = { command = "swift-format", args = [
  "--configuration",
  "/Users/enth/.config/swift/format.json",
] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "deno", args = ["fmt", "-", "--ext", "md"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typst$"
file-types = ["typ"]
comment-token = "//"
indent = { tab-width = 2, unit = " " }
roots = []
language-servers = ["typst-lsp"]

# MARK: - Web Development

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/Users/enth/.bun/install/global/node_modules/typescript/lib" }, environment = "node" }

[[language]]
name = "astro"
auto-format = true
language-servers = ["astro-ls"]

[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-ls"]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "emmet-ls"]
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true
